// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitcolibri/birdFeed/v1/query.proto

package birdFeed

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetTweetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetTweetRequest) Reset()         { *m = QueryGetTweetRequest{} }
func (m *QueryGetTweetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTweetRequest) ProtoMessage()    {}
func (*QueryGetTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{0}
}
func (m *QueryGetTweetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTweetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTweetRequest.Merge(m, src)
}
func (m *QueryGetTweetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTweetRequest proto.InternalMessageInfo

func (m *QueryGetTweetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetTweetResponse struct {
	Tweet    *Tweet   `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	Comments []*Tweet `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (m *QueryGetTweetResponse) Reset()         { *m = QueryGetTweetResponse{} }
func (m *QueryGetTweetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTweetResponse) ProtoMessage()    {}
func (*QueryGetTweetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{1}
}
func (m *QueryGetTweetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTweetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTweetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTweetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTweetResponse.Merge(m, src)
}
func (m *QueryGetTweetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTweetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTweetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTweetResponse proto.InternalMessageInfo

func (m *QueryGetTweetResponse) GetTweet() *Tweet {
	if m != nil {
		return m.Tweet
	}
	return nil
}

func (m *QueryGetTweetResponse) GetComments() []*Tweet {
	if m != nil {
		return m.Comments
	}
	return nil
}

type QueryGetAuthorTweetsRequest struct {
	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (m *QueryGetAuthorTweetsRequest) Reset()         { *m = QueryGetAuthorTweetsRequest{} }
func (m *QueryGetAuthorTweetsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuthorTweetsRequest) ProtoMessage()    {}
func (*QueryGetAuthorTweetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{2}
}
func (m *QueryGetAuthorTweetsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuthorTweetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuthorTweetsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuthorTweetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuthorTweetsRequest.Merge(m, src)
}
func (m *QueryGetAuthorTweetsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuthorTweetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuthorTweetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuthorTweetsRequest proto.InternalMessageInfo

func (m *QueryGetAuthorTweetsRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type QueryGetAuthorTweetsResponse struct {
	Tweets []*Tweet `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
}

func (m *QueryGetAuthorTweetsResponse) Reset()         { *m = QueryGetAuthorTweetsResponse{} }
func (m *QueryGetAuthorTweetsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuthorTweetsResponse) ProtoMessage()    {}
func (*QueryGetAuthorTweetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{3}
}
func (m *QueryGetAuthorTweetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuthorTweetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuthorTweetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuthorTweetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuthorTweetsResponse.Merge(m, src)
}
func (m *QueryGetAuthorTweetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuthorTweetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuthorTweetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuthorTweetsResponse proto.InternalMessageInfo

func (m *QueryGetAuthorTweetsResponse) GetTweets() []*Tweet {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type QueryGetTweetLikesRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetTweetLikesRequest) Reset()         { *m = QueryGetTweetLikesRequest{} }
func (m *QueryGetTweetLikesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTweetLikesRequest) ProtoMessage()    {}
func (*QueryGetTweetLikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{4}
}
func (m *QueryGetTweetLikesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTweetLikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTweetLikesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTweetLikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTweetLikesRequest.Merge(m, src)
}
func (m *QueryGetTweetLikesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTweetLikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTweetLikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTweetLikesRequest proto.InternalMessageInfo

func (m *QueryGetTweetLikesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetTweetLikesResponse struct {
	Likes []string `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (m *QueryGetTweetLikesResponse) Reset()         { *m = QueryGetTweetLikesResponse{} }
func (m *QueryGetTweetLikesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTweetLikesResponse) ProtoMessage()    {}
func (*QueryGetTweetLikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{5}
}
func (m *QueryGetTweetLikesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTweetLikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTweetLikesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTweetLikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTweetLikesResponse.Merge(m, src)
}
func (m *QueryGetTweetLikesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTweetLikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTweetLikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTweetLikesResponse proto.InternalMessageInfo

func (m *QueryGetTweetLikesResponse) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

type QueryGetUserRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetUserRequest) Reset()         { *m = QueryGetUserRequest{} }
func (m *QueryGetUserRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserRequest) ProtoMessage()    {}
func (*QueryGetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{6}
}
func (m *QueryGetUserRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserRequest.Merge(m, src)
}
func (m *QueryGetUserRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserRequest proto.InternalMessageInfo

func (m *QueryGetUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *QueryGetUserResponse) Reset()         { *m = QueryGetUserResponse{} }
func (m *QueryGetUserResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserResponse) ProtoMessage()    {}
func (*QueryGetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{7}
}
func (m *QueryGetUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserResponse.Merge(m, src)
}
func (m *QueryGetUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserResponse proto.InternalMessageInfo

func (m *QueryGetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type QueryGetUserFollowersRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetUserFollowersRequest) Reset()         { *m = QueryGetUserFollowersRequest{} }
func (m *QueryGetUserFollowersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserFollowersRequest) ProtoMessage()    {}
func (*QueryGetUserFollowersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{8}
}
func (m *QueryGetUserFollowersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserFollowersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserFollowersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserFollowersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserFollowersRequest.Merge(m, src)
}
func (m *QueryGetUserFollowersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserFollowersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserFollowersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserFollowersRequest proto.InternalMessageInfo

func (m *QueryGetUserFollowersRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetUserFollowersResponse struct {
	Followers []string `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
}

func (m *QueryGetUserFollowersResponse) Reset()         { *m = QueryGetUserFollowersResponse{} }
func (m *QueryGetUserFollowersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserFollowersResponse) ProtoMessage()    {}
func (*QueryGetUserFollowersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{9}
}
func (m *QueryGetUserFollowersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserFollowersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserFollowersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserFollowersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserFollowersResponse.Merge(m, src)
}
func (m *QueryGetUserFollowersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserFollowersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserFollowersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserFollowersResponse proto.InternalMessageInfo

func (m *QueryGetUserFollowersResponse) GetFollowers() []string {
	if m != nil {
		return m.Followers
	}
	return nil
}

type QueryGetUserFollowsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetUserFollowsRequest) Reset()         { *m = QueryGetUserFollowsRequest{} }
func (m *QueryGetUserFollowsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserFollowsRequest) ProtoMessage()    {}
func (*QueryGetUserFollowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{10}
}
func (m *QueryGetUserFollowsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserFollowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserFollowsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserFollowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserFollowsRequest.Merge(m, src)
}
func (m *QueryGetUserFollowsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserFollowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserFollowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserFollowsRequest proto.InternalMessageInfo

func (m *QueryGetUserFollowsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetUserFollowsResponse struct {
	Follows []string `protobuf:"bytes,1,rep,name=follows,proto3" json:"follows,omitempty"`
}

func (m *QueryGetUserFollowsResponse) Reset()         { *m = QueryGetUserFollowsResponse{} }
func (m *QueryGetUserFollowsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserFollowsResponse) ProtoMessage()    {}
func (*QueryGetUserFollowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a4f1e2044a41033, []int{11}
}
func (m *QueryGetUserFollowsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserFollowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserFollowsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserFollowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserFollowsResponse.Merge(m, src)
}
func (m *QueryGetUserFollowsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserFollowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserFollowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserFollowsResponse proto.InternalMessageInfo

func (m *QueryGetUserFollowsResponse) GetFollows() []string {
	if m != nil {
		return m.Follows
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetTweetRequest)(nil), "bitcolibri.birdFeed.v1.QueryGetTweetRequest")
	proto.RegisterType((*QueryGetTweetResponse)(nil), "bitcolibri.birdFeed.v1.QueryGetTweetResponse")
	proto.RegisterType((*QueryGetAuthorTweetsRequest)(nil), "bitcolibri.birdFeed.v1.QueryGetAuthorTweetsRequest")
	proto.RegisterType((*QueryGetAuthorTweetsResponse)(nil), "bitcolibri.birdFeed.v1.QueryGetAuthorTweetsResponse")
	proto.RegisterType((*QueryGetTweetLikesRequest)(nil), "bitcolibri.birdFeed.v1.QueryGetTweetLikesRequest")
	proto.RegisterType((*QueryGetTweetLikesResponse)(nil), "bitcolibri.birdFeed.v1.QueryGetTweetLikesResponse")
	proto.RegisterType((*QueryGetUserRequest)(nil), "bitcolibri.birdFeed.v1.QueryGetUserRequest")
	proto.RegisterType((*QueryGetUserResponse)(nil), "bitcolibri.birdFeed.v1.QueryGetUserResponse")
	proto.RegisterType((*QueryGetUserFollowersRequest)(nil), "bitcolibri.birdFeed.v1.QueryGetUserFollowersRequest")
	proto.RegisterType((*QueryGetUserFollowersResponse)(nil), "bitcolibri.birdFeed.v1.QueryGetUserFollowersResponse")
	proto.RegisterType((*QueryGetUserFollowsRequest)(nil), "bitcolibri.birdFeed.v1.QueryGetUserFollowsRequest")
	proto.RegisterType((*QueryGetUserFollowsResponse)(nil), "bitcolibri.birdFeed.v1.QueryGetUserFollowsResponse")
}

func init() {
	proto.RegisterFile("bitcolibri/birdFeed/v1/query.proto", fileDescriptor_8a4f1e2044a41033)
}

var fileDescriptor_8a4f1e2044a41033 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xb1, 0x6f, 0xd3, 0x4e,
	0x14, 0xc7, 0x7b, 0xf9, 0xfd, 0xda, 0x24, 0x0f, 0x51, 0xd0, 0x11, 0xaa, 0xe0, 0xa6, 0x56, 0x75,
	0x42, 0x55, 0xd4, 0x16, 0x5f, 0xe2, 0x34, 0x50, 0x84, 0x3a, 0xc0, 0x50, 0x18, 0x58, 0x88, 0xe8,
	0xc2, 0x96, 0xc4, 0x47, 0x6a, 0x91, 0xe4, 0x52, 0xdf, 0xa5, 0x55, 0x15, 0x65, 0x61, 0x81, 0x11,
	0x89, 0x05, 0x76, 0x56, 0x24, 0x26, 0x24, 0x16, 0x66, 0xc6, 0x4a, 0x2c, 0x8c, 0x28, 0x41, 0xe2,
	0xdf, 0x40, 0xb6, 0xcf, 0x71, 0x13, 0xd9, 0x8a, 0x33, 0xc5, 0xf7, 0xf4, 0xbe, 0xef, 0x7d, 0xee,
	0xdd, 0xfb, 0x2a, 0x40, 0x1a, 0xb6, 0x6c, 0xf2, 0xb6, 0xdd, 0x70, 0x6c, 0xda, 0xb0, 0x1d, 0xeb,
	0x90, 0x31, 0x8b, 0x9e, 0x96, 0xe9, 0x49, 0x9f, 0x39, 0xe7, 0x46, 0xcf, 0xe1, 0x92, 0xe3, 0xb5,
	0x30, 0xc7, 0x08, 0x72, 0x8c, 0xd3, 0xb2, 0x16, 0xa7, 0x95, 0xe7, 0x3d, 0x26, 0x7c, 0xad, 0xb6,
	0xde, 0xe4, 0xa2, 0xc3, 0x85, 0x5f, 0x6f, 0xa6, 0xb0, 0x96, 0x6b, 0xf1, 0x16, 0xf7, 0x3e, 0xa9,
	0xfb, 0xa5, 0xa2, 0x85, 0x16, 0xe7, 0xad, 0x36, 0xa3, 0xf5, 0x9e, 0x4d, 0xeb, 0xdd, 0x2e, 0x97,
	0x75, 0x69, 0xf3, 0xae, 0x2a, 0x48, 0xb6, 0x20, 0xf7, 0xcc, 0x2d, 0xf1, 0x98, 0xc9, 0xe7, 0x67,
	0x8c, 0xc9, 0x1a, 0x3b, 0xe9, 0x33, 0x21, 0xf1, 0x2a, 0xa4, 0x6c, 0x2b, 0x8f, 0x36, 0x51, 0x31,
	0x5b, 0x4b, 0xd9, 0x16, 0x79, 0x83, 0xe0, 0xe6, 0x4c, 0xa2, 0xe8, 0xf1, 0xae, 0x60, 0xb8, 0x02,
	0xcb, 0xd2, 0x0d, 0x78, 0xc9, 0x57, 0xcc, 0x0d, 0x23, 0xfa, 0x7a, 0x86, 0xaf, 0xf2, 0x73, 0xf1,
	0x7d, 0xc8, 0x34, 0x79, 0xa7, 0xc3, 0xba, 0x52, 0xe4, 0x53, 0x9b, 0xff, 0xcd, 0xd7, 0x4d, 0xd2,
	0x49, 0x15, 0xd6, 0x03, 0x90, 0x87, 0x7d, 0x79, 0xcc, 0x1d, 0x2f, 0x41, 0x04, 0xe0, 0x6b, 0xb0,
	0x52, 0xf7, 0xc2, 0x0a, 0x5e, 0x9d, 0xc8, 0x11, 0x14, 0xa2, 0x65, 0xea, 0x1a, 0x55, 0x58, 0xf1,
	0xd0, 0x44, 0x1e, 0x25, 0xe1, 0x51, 0xc9, 0x64, 0x07, 0x6e, 0x4d, 0x8d, 0xe5, 0xa9, 0xfd, 0x8a,
	0x89, 0xb8, 0x21, 0x9a, 0xa0, 0x45, 0x25, 0x2b, 0x82, 0x1c, 0x2c, 0xb7, 0xdd, 0x80, 0x07, 0x90,
	0xad, 0xf9, 0x07, 0x42, 0xe1, 0x46, 0xa0, 0x39, 0x12, 0xcc, 0x09, 0x4a, 0xe7, 0x21, 0x5d, 0xb7,
	0x2c, 0x87, 0x09, 0xa1, 0xea, 0x07, 0x47, 0xf2, 0x24, 0x7c, 0x51, 0x5f, 0xa0, 0xca, 0x97, 0xe0,
	0xff, 0xbe, 0x60, 0x8e, 0x7a, 0xa6, 0x42, 0xdc, 0xf5, 0x3c, 0x8d, 0x97, 0x49, 0xf6, 0xc3, 0x91,
	0xb9, 0xd1, 0x43, 0xde, 0x6e, 0xf3, 0x33, 0xe6, 0x88, 0xf9, 0x0c, 0x07, 0xb0, 0x11, 0xa3, 0x54,
	0x30, 0x05, 0xc8, 0xbe, 0x0c, 0x82, 0xea, 0xbe, 0x61, 0x80, 0xdc, 0x0d, 0xe7, 0x14, 0xca, 0x13,
	0xb4, 0xbd, 0x17, 0xae, 0xc6, 0x94, 0x4e, 0x35, 0xcd, 0x43, 0xda, 0xef, 0x11, 0xb4, 0x0c, 0x8e,
	0xe6, 0xa7, 0x0c, 0x2c, 0x7b, 0x4a, 0xfc, 0x01, 0x41, 0x26, 0x78, 0x1e, 0xbc, 0x1b, 0x37, 0xa4,
	0x28, 0xcb, 0x68, 0x77, 0x12, 0x66, 0xfb, 0x34, 0x84, 0xbe, 0xfd, 0xfb, 0x65, 0x1b, 0xbd, 0xfe,
	0xf9, 0xe7, 0x7d, 0xea, 0x36, 0x26, 0x34, 0xce, 0xfc, 0xae, 0x86, 0x0e, 0x6c, 0x6b, 0x88, 0xbf,
	0x21, 0xb8, 0x36, 0xb3, 0xbd, 0xb8, 0x32, 0xaf, 0x67, 0x84, 0x45, 0xb4, 0xbd, 0xc5, 0x44, 0x8a,
	0xf7, 0x41, 0xc8, 0x5b, 0xc2, 0x46, 0x1c, 0xaf, 0xef, 0x36, 0x3a, 0xf0, 0x7f, 0x87, 0x3e, 0xbf,
	0xc0, 0x9f, 0x11, 0x5c, 0x9d, 0xda, 0x7a, 0x5c, 0x4e, 0x34, 0xad, 0xcb, 0x76, 0xd2, 0xcc, 0x45,
	0x24, 0x8a, 0xba, 0x1a, 0x52, 0x6f, 0xe3, 0xe2, 0xfc, 0x29, 0x53, 0xcf, 0x75, 0xf8, 0x23, 0x82,
	0xb4, 0xda, 0x22, 0xbc, 0x33, 0xaf, 0xed, 0x25, 0x5f, 0x6a, 0xbb, 0xc9, 0x92, 0x15, 0x5d, 0x25,
	0xa4, 0x2b, 0xe2, 0xad, 0x38, 0x3a, 0xd7, 0x8c, 0x74, 0xa0, 0x96, 0x7c, 0x88, 0xbf, 0x23, 0xb8,
	0x3e, 0x6b, 0x2c, 0xbc, 0x97, 0xa4, 0xef, 0xac, 0x83, 0xb5, 0xea, 0x82, 0x2a, 0x85, 0x7d, 0x10,
	0x62, 0x9b, 0xb8, 0x94, 0x0c, 0x9b, 0x4e, 0xec, 0x8d, 0xbf, 0x22, 0x58, 0x9d, 0xb6, 0x28, 0x36,
	0x93, 0x83, 0x4c, 0xe0, 0x2b, 0x0b, 0x69, 0x16, 0xda, 0xe2, 0x48, 0x74, 0xf1, 0x68, 0xff, 0xc7,
	0x48, 0x47, 0x17, 0x23, 0x1d, 0xfd, 0x1e, 0xe9, 0xe8, 0xdd, 0x58, 0x5f, 0xba, 0x18, 0xeb, 0x4b,
	0xbf, 0xc6, 0xfa, 0xd2, 0x0b, 0xbd, 0x65, 0xcb, 0xe3, 0x7e, 0xc3, 0x68, 0xf2, 0x4e, 0x54, 0xcd,
	0xc6, 0x8a, 0xf7, 0x6f, 0x5b, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x1b, 0xb7, 0xf8, 0x20,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GetTweet(ctx context.Context, in *QueryGetTweetRequest, opts ...grpc.CallOption) (*QueryGetTweetResponse, error)
	GetAuthorTweets(ctx context.Context, in *QueryGetAuthorTweetsRequest, opts ...grpc.CallOption) (*QueryGetAuthorTweetsResponse, error)
	GetTweetLikes(ctx context.Context, in *QueryGetTweetLikesRequest, opts ...grpc.CallOption) (*QueryGetTweetLikesResponse, error)
	GetUser(ctx context.Context, in *QueryGetUserRequest, opts ...grpc.CallOption) (*QueryGetUserResponse, error)
	GetUserFollowers(ctx context.Context, in *QueryGetUserFollowersRequest, opts ...grpc.CallOption) (*QueryGetUserFollowersResponse, error)
	GetUserFollows(ctx context.Context, in *QueryGetUserFollowsRequest, opts ...grpc.CallOption) (*QueryGetUserFollowsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetTweet(ctx context.Context, in *QueryGetTweetRequest, opts ...grpc.CallOption) (*QueryGetTweetResponse, error) {
	out := new(QueryGetTweetResponse)
	err := c.cc.Invoke(ctx, "/bitcolibri.birdFeed.v1.Query/GetTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAuthorTweets(ctx context.Context, in *QueryGetAuthorTweetsRequest, opts ...grpc.CallOption) (*QueryGetAuthorTweetsResponse, error) {
	out := new(QueryGetAuthorTweetsResponse)
	err := c.cc.Invoke(ctx, "/bitcolibri.birdFeed.v1.Query/GetAuthorTweets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTweetLikes(ctx context.Context, in *QueryGetTweetLikesRequest, opts ...grpc.CallOption) (*QueryGetTweetLikesResponse, error) {
	out := new(QueryGetTweetLikesResponse)
	err := c.cc.Invoke(ctx, "/bitcolibri.birdFeed.v1.Query/GetTweetLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUser(ctx context.Context, in *QueryGetUserRequest, opts ...grpc.CallOption) (*QueryGetUserResponse, error) {
	out := new(QueryGetUserResponse)
	err := c.cc.Invoke(ctx, "/bitcolibri.birdFeed.v1.Query/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUserFollowers(ctx context.Context, in *QueryGetUserFollowersRequest, opts ...grpc.CallOption) (*QueryGetUserFollowersResponse, error) {
	out := new(QueryGetUserFollowersResponse)
	err := c.cc.Invoke(ctx, "/bitcolibri.birdFeed.v1.Query/GetUserFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUserFollows(ctx context.Context, in *QueryGetUserFollowsRequest, opts ...grpc.CallOption) (*QueryGetUserFollowsResponse, error) {
	out := new(QueryGetUserFollowsResponse)
	err := c.cc.Invoke(ctx, "/bitcolibri.birdFeed.v1.Query/GetUserFollows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GetTweet(context.Context, *QueryGetTweetRequest) (*QueryGetTweetResponse, error)
	GetAuthorTweets(context.Context, *QueryGetAuthorTweetsRequest) (*QueryGetAuthorTweetsResponse, error)
	GetTweetLikes(context.Context, *QueryGetTweetLikesRequest) (*QueryGetTweetLikesResponse, error)
	GetUser(context.Context, *QueryGetUserRequest) (*QueryGetUserResponse, error)
	GetUserFollowers(context.Context, *QueryGetUserFollowersRequest) (*QueryGetUserFollowersResponse, error)
	GetUserFollows(context.Context, *QueryGetUserFollowsRequest) (*QueryGetUserFollowsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetTweet(ctx context.Context, req *QueryGetTweetRequest) (*QueryGetTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTweet not implemented")
}
func (*UnimplementedQueryServer) GetAuthorTweets(ctx context.Context, req *QueryGetAuthorTweetsRequest) (*QueryGetAuthorTweetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorTweets not implemented")
}
func (*UnimplementedQueryServer) GetTweetLikes(ctx context.Context, req *QueryGetTweetLikesRequest) (*QueryGetTweetLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTweetLikes not implemented")
}
func (*UnimplementedQueryServer) GetUser(ctx context.Context, req *QueryGetUserRequest) (*QueryGetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedQueryServer) GetUserFollowers(ctx context.Context, req *QueryGetUserFollowersRequest) (*QueryGetUserFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollowers not implemented")
}
func (*UnimplementedQueryServer) GetUserFollows(ctx context.Context, req *QueryGetUserFollowsRequest) (*QueryGetUserFollowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollows not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcolibri.birdFeed.v1.Query/GetTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTweet(ctx, req.(*QueryGetTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAuthorTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAuthorTweetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAuthorTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcolibri.birdFeed.v1.Query/GetAuthorTweets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAuthorTweets(ctx, req.(*QueryGetAuthorTweetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTweetLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTweetLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTweetLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcolibri.birdFeed.v1.Query/GetTweetLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTweetLikes(ctx, req.(*QueryGetTweetLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcolibri.birdFeed.v1.Query/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUser(ctx, req.(*QueryGetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUserFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUserFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcolibri.birdFeed.v1.Query/GetUserFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUserFollowers(ctx, req.(*QueryGetUserFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUserFollows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserFollowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUserFollows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitcolibri.birdFeed.v1.Query/GetUserFollows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUserFollows(ctx, req.(*QueryGetUserFollowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bitcolibri.birdFeed.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTweet",
			Handler:    _Query_GetTweet_Handler,
		},
		{
			MethodName: "GetAuthorTweets",
			Handler:    _Query_GetAuthorTweets_Handler,
		},
		{
			MethodName: "GetTweetLikes",
			Handler:    _Query_GetTweetLikes_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Query_GetUser_Handler,
		},
		{
			MethodName: "GetUserFollowers",
			Handler:    _Query_GetUserFollowers_Handler,
		},
		{
			MethodName: "GetUserFollows",
			Handler:    _Query_GetUserFollows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitcolibri/birdFeed/v1/query.proto",
}

func (m *QueryGetTweetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTweetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTweetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTweetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTweetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTweetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Comments) > 0 {
		for iNdEx := len(m.Comments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Comments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Tweet != nil {
		{
			size, err := m.Tweet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuthorTweetsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuthorTweetsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuthorTweetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuthorTweetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuthorTweetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuthorTweetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tweets) > 0 {
		for iNdEx := len(m.Tweets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tweets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTweetLikesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTweetLikesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTweetLikesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTweetLikesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTweetLikesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTweetLikesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Likes) > 0 {
		for iNdEx := len(m.Likes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Likes[iNdEx])
			copy(dAtA[i:], m.Likes[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Likes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.User != nil {
		{
			size, err := m.User.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserFollowersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserFollowersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserFollowersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserFollowersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserFollowersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserFollowersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Followers) > 0 {
		for iNdEx := len(m.Followers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Followers[iNdEx])
			copy(dAtA[i:], m.Followers[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Followers[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserFollowsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserFollowsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserFollowsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserFollowsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserFollowsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserFollowsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Follows) > 0 {
		for iNdEx := len(m.Follows) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Follows[iNdEx])
			copy(dAtA[i:], m.Follows[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Follows[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetTweetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTweetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tweet != nil {
		l = m.Tweet.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Comments) > 0 {
		for _, e := range m.Comments {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetAuthorTweetsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAuthorTweetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tweets) > 0 {
		for _, e := range m.Tweets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetTweetLikesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTweetLikesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Likes) > 0 {
		for _, s := range m.Likes {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetUserRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.User != nil {
		l = m.User.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserFollowersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserFollowersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Followers) > 0 {
		for _, s := range m.Followers {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetUserFollowsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserFollowsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Follows) > 0 {
		for _, s := range m.Follows {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetTweetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTweetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTweetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTweetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTweetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTweetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tweet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tweet == nil {
				m.Tweet = &Tweet{}
			}
			if err := m.Tweet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = append(m.Comments, &Tweet{})
			if err := m.Comments[len(m.Comments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuthorTweetsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuthorTweetsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuthorTweetsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuthorTweetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuthorTweetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuthorTweetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tweets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tweets = append(m.Tweets, &Tweet{})
			if err := m.Tweets[len(m.Tweets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTweetLikesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTweetLikesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTweetLikesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTweetLikesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTweetLikesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTweetLikesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Likes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Likes = append(m.Likes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.User == nil {
				m.User = &User{}
			}
			if err := m.User.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserFollowersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserFollowersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserFollowersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserFollowersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserFollowersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserFollowersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Followers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Followers = append(m.Followers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserFollowsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserFollowsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserFollowsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserFollowsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserFollowsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserFollowsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Follows", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Follows = append(m.Follows, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
